### ISSUE TITLE
Crear README.MD Inicial 

### ISSUE THREAD

**Issue by fdemian** [UTNianos/2.0#10]
Readme de primeros pasos. El mismo debe tener la secuencia ordenada de pasos que nos permitan arrancar la aplicación.

**Comment by fdemian** [comment]
Ver https://gist.github.com/fdemian/eeaf0498d2331f7d7465aa6a7cd93556 . Tendríamos que tener un build structure asi de facil mínimo (o más, los pasos se pueden juntar en un solo script, pero esa secuencia es irreducible). El README estaba hecho para Python, pero no debería ser imposible hacer lo mismo para PHP.

**Comment by Javier-Rotelli** [comment]
yo soy un poco reacio a poner como instalar las cosas, porque te atas a un entorno en particular. prefiero armar una lista de cosas que tenes que tener y dejar que cada uno se lo instale.
lo demas, en el readme que tenemos ahora esta todo creo. hay un par de cosas que habria que actualizar, como los comandos para correr los tests y el linter, pero lo demas es asi como esta puesto en el readme actual

**Comment by fdemian** [comment]
El entorno ya esta, no estamos atando a nadie mas que los que los estamos atando a usar el stack que tenemos. Si quieren pueden arrancar el entorno dentro de un jail, un chroot o lo que sea eso es cosa del usuario (si te hace ruido esto lo podemos aclarar especificamente).

El README que tenemos actualmente es bastante poco informativo y no le da una idea a nadie de como instalar el repo. Si pretendemos que alguien use el software (o incluso generalizarlo para que lo use más gente) necesitamos una secuencia de instalación que requiera poco esfuerzo de parte del usuario.

**Comment by Javier-Rotelli** [comment]
a que te referis con instalacion? actualmente no tenemos proceso de deploy...

**Comment by fdemian** [comment]
A una secuencia de pasos ordenada, la cual, al seguirla resulte en una instancia del programa (e.d: el backend) corriendo en la computadora del usuario. 

No es todo el proceso de deploy esto, sencillamente los pasos para correr una instancia del backend.
