### ISSUE TITLE
Encapsular TinyMCE en un componente de knockout

### ISSUE THREAD

**Issue by Javier-Rotelli** [UTNianos/2.0#6]
fijate, yo empece a hacerlo aca: https://github.com/UTNianos/2.0/tree/master/resources/assets/js/ko/components/editor

la idea es tener un componente por carpeta con todas sus dependencias ahi.

**Comment by fdemian** [comment]
@Javier-Rotelli  estuve experimentando un poco con Alloy-Editor que habías mencionado y termine con esto: 

http://fdemian.github.io/PhorumEditorTest/

Estaría bueno ver que opinan @gonnza  y @julianSelser .

**Comment by Javier-Rotelli** [comment]
con que lo armaste? react? knockout?

**Comment by fdemian** [comment]
React. Lo estoy usando en uno de los JS para crear el boton de spoiler (que es el boton de marquee porque no encontre como cambiarlo todavía). De todas formas, fuera de eso no hay que preocuparse por React porque el JS de alloy lo usa internamente, pero esta encapsulado. 

Ahora tendría que ver como poner bien el boton de spoiler (la idea es que en vez de crear un elemento spoiler cree un span con class="spoiler concealed").

**Comment by fdemian** [comment]
Esto no pertenece más aca desde la separación del frontend. BTW, ya que estamos usando react para todo el proyecto, algo hecho en React nos conviene más. Esto es lo que tengo hasta ahora (si, es un WIP todavía pero esta bastante avanzado): 

https://fdemian.github.io/EditorDemo/

Cierro esto porque no pertenece más al backend.
